# Generated by Django 2.2.12 on 2021-09-16 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('phone', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('birthday', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('email', models.EmailField(max_length=254)),
                ('phone', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('id_number', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('description', models.CharField(blank=True, max_length=150, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('date_of_purchase', models.DateTimeField(auto_now_add=True, null=True)),
                ('purchase_no', models.AutoField(primary_key=True, serialize=False)),
                ('purchase_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('product', models.CharField(max_length=254)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('VAT', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('Bank', 'Bank'), ('Mpesa', 'Mpesa')], max_length=254)),
                ('status', models.CharField(choices=[('Paid', 'Paid'), ('Not Paid', 'Not Paid')], max_length=254)),
                ('branch', models.CharField(choices=[('feruzi', 'feruzi'), ('fourways', 'fourways')], max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('percentage', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('sales_no', models.AutoField(primary_key=True, serialize=False)),
                ('sales_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('amount', models.IntegerField()),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('Bank', 'Bank'), ('Mpesa', 'Mpesa')], max_length=20)),
                ('branch', models.CharField(choices=[('feruzi', 'feruzi'), ('fourways', 'fourways')], max_length=20)),
                ('date_of_sale', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(choices=[('feruzi', 'feruzi'), ('fourways', 'fourways')], max_length=254)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('invoice_no', models.AutoField(primary_key=True, serialize=False)),
                ('invoice_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('date_of_services', models.DateTimeField(auto_now_add=True, null=True)),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('Bank', 'Bank'), ('Mpesa', 'Mpesa')], max_length=254)),
                ('branch', models.CharField(choices=[('feruzi', 'feruzi'), ('fourways', 'fourways')], default='fourways', max_length=254)),
                ('Total', models.IntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Customer')),
                ('served_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Employee')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Service')),
            ],
        ),
    ]
