# Generated by Django 2.2.12 on 2021-09-13 06:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20210913_0542'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('sales_no', models.AutoField(primary_key=True, serialize=False)),
                ('sales_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('amount', models.IntegerField()),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('Bank', 'Bank'), ('Mpesa', 'Mpesa')], max_length=20)),
                ('branch', models.CharField(choices=[('feruzi', 'feruzi'), ('fourways', 'fourways')], max_length=20)),
                ('date_of_sale', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Product')),
            ],
        ),
    ]
