# Generated by Django 3.1.7 on 2021-05-16 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20210516_1020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='amount',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='Total',
            field=models.IntegerField(),
        ),
    ]
