# Generated by Django 2.2.12 on 2021-09-13 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='percentage',
            field=models.IntegerField(default=40),
            preserve_default=False,
        ),
    ]
