# Generated by Django 3.1.7 on 2021-05-19 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20210516_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='date_of_services',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
