# Generated by Django 2.2.12 on 2021-09-15 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_service_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='percentage',
            field=models.IntegerField(default=40),
            preserve_default=False,
        ),
    ]
