# Generated by Django 3.1.7 on 2021-05-19 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20210519_0614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='date_of_purchase',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
