# Generated by Django 3.1.7 on 2021-05-20 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20210519_0635'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=20)),
                ('customers_served', models.IntegerField()),
                ('total', models.IntegerField()),
                ('commission', models.DecimalField(decimal_places=2, max_digits=7)),
                ('deductions', models.IntegerField()),
                ('bonus', models.IntegerField()),
                ('salary', models.DecimalField(decimal_places=2, max_digits=7)),
                ('status', models.CharField(choices=[('Paid', 'Paid'), ('Not Paid', 'Not Paid')], max_length=254)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.employee')),
            ],
        ),
    ]
