# Generated by Django 3.1.7 on 2021-05-26 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_payroll'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payroll',
            name='bonus',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='deductions',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='salary',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='status',
        ),
    ]
