# Generated by Django 3.1.7 on 2021-06-06 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20210528_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='branch',
            field=models.CharField(choices=[('feruzi', 'feruzi'), ('fourways', 'fourways')], default='feruzi', max_length=254),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Payroll',
        ),
    ]
